#!/bin/bash
SHELL=/bin/bash
PATH="$PATH:/home/repo/bin"
screen -dmS repo
sleep 1
screen -S repo -p 0 -X exec sh irc
sleep 1
screen -S repo -X screen
sleep 1
screen -S repo -p 1 -X number 0
sleep 1
screen -S repo -p 0 -X exec sh repograb
